### ISSUE TITLE
Remove QgsServerProjectParser

### ISSUE THREAD

**Issue by m-kuhn** [qgis/qgis3.0_api#57]

**Comment by wonder-sk** [comment]
Related to #8

**Comment by rldhont** [comment]
Hi @m-kuhn 
Because I'd like to fix an issue server side I discovered that QgsServerProjectParser has been made to:
- do not load all the layers at each request
- have access to secret readXml method

For example, if I want to reload vector joins from a QgsVectorLayer, I only have readLayerXml. But this method do too many things.

So a proper point will be also to update the QgsVectorLayer API.

**Comment by m-kuhn** [comment]
@rldhont I think that was a (partial) goal of the grant proposal of @wonder-sk which unfortunately did not make it. I think it would be great to check if someone could fund this project through separate channels.

**Comment by pcav** [comment]
@m-kuhn good idea, please let the community know. I think something can be done.

**Comment by m-kuhn** [comment]
I'm not really involved in this. I think it's best if someone close to clients using server or @wonder-sk / lutra as developer could step in.

**Comment by haubourg** [comment]
@rldhont @pblottiere , Is the  QgsServerProjectParser squizzed out everywhere in the code ? Do we still have parts of the code to rework to reach that important target?

**Comment by rldhont** [comment]
These are already merged:
https://github.com/qgis/QGIS/pull/4157
https://github.com/qgis/QGIS/pull/4344
https://github.com/qgis/QGIS/pull/4415
https://github.com/qgis/QGIS/pull/4597

It's a work in progress:
https://github.com/qgis/QGIS/pull/4313

**Comment by rldhont** [comment]
With https://github.com/qgis/QGIS/pull/4959 merged, QgsServerProjectParser has been removed.
I think this issue can be closed
