### ISSUE TITLE
Remove visitor pattern from QgsExpression

### ISSUE THREAD

**Issue by m-kuhn** [qgis/qgis3.0_api#64]
QgsExpression supports the visitor pattern but it is currently unused throughout our codebase (and I don't think used outside either). The major candidate for this would have been the expression compiler which is now implemented with a different approach.

I think we should remove it to keep the code a little slicker and in case we will need it for something it can easily be reintroduced.

@wonder-sk

**Comment by NathanW2** [comment]
The main question is why it's not used when the pattern is good for that
use case?

**Comment by m-kuhn** [comment]
Because it wasn't so good for that use case.
I can't find the discussion but in the end I think the problem was you'd need an additional argument to the accept method for which the type cannot be defined. The current approach doesn't have this problem and I think we can say it has proven to be stable.

**Comment by wonder-sk** [comment]
I don't mind if it gets removed... It is easier to traverse the expression tree just with one recursive function rather than fiddling with visitor.

I get the impression the pattern makes more sense in different scenarios - 1) if the internal structure is opaque (not allowed) to access internals directory or 2) there are various traversing/filtering strategies, so visitor may be used to avoid code duplication.
