### ISSUE TITLE
new version of PROJ.4

### ISSUE THREAD

**Issue by 3nids** [qgis/qgis3.0_api#82]
It seems a new version is to be released.

Does it had any implication for us on QGIS 3.0 API?
Any idea on the time frame?

ping @rouault @kbevers

**Comment by kbevers** [comment]
> Does it had any implication for us on QGIS 3.0 API?

In the short run, no. In long run, yes. See the preliminary release notes here: https://github.com/kbevers/proj.4/blob/90f592eb13cc120898e250996a228124725e5731/NEWS

Hopefully the first release candidate will be out next week. I am aiming for february 15 for the final release.

**Comment by nyalldawson** [comment]
I don't think this is a major change for us. All our proj library usage is siloed away in single cpp files, and none is exposed to the public api.

The new transform contexts mean we're ready for temporal projections (at least with QgsCoordinateTransform - we still need a way to set timestamps for geometries in order to do dynamic projections. But that's minor.)

**Comment by kbevers** [comment]
@nyalldawson is the use of PROJ in QGIS limited to functions from `proj_api.h`? Or do you also use stuff from `projects.h`?

**Comment by jef-n** [comment]
@kbevers only `proj_api.h`

**Comment by kbevers** [comment]
Alright, then QGIS should be set for at least the next two years. We are planning on removing `projects.h` from the public interface in version 6.0.0 in about a years time. `proj_api.h` will be removed with v. 7.0.0 that at the moment is scheduled to be released in 2020. So I'd advice that you start looking at switching to the new API in a year or so. I am of course available if any help is needed :-)

**Comment by nyalldawson** [comment]
@kbevers I think we'll need to add compatibility well before that, at least so that we're ready for GDA2020 and the other dynamic projection systems. But I still think all the changes will be isolated to 1 or 2 private files, so we can #ifdef in branches for the newer proj API as soon as we're both ready.

**Comment by 3nids** [comment]
thanks for the followup, feel free to close it!

**Comment by idanmiara** [comment]
@jef-n  @kbevers
Hi,
I would like to test PROJ v5 on Windows.
Currently I use PROJ v4.9.3-1 from OSGeo4W/QGIS 2.99 setup.
I can't find PROJ v5 in OSGeo4W setup, Would PROJ v5 replace v4 in QGIS 3.0/OSGeo4W anytime soon?
Otherwise, are there Windows x64 binaries available someplace else? or building instructions for MSVC?

**Comment by kbevers** [comment]
> or building instructions for MSVC?

There's build instructions for Windows in the README.

**Comment by idanmiara** [comment]
Thanks, I'll try to build it.

**Comment by nyalldawson** [comment]
Not a part of stable qgis API, so can be done at anytime
